#!/bin/bash
#Author Leo G

#DECLARE VARIABLES
backup_dir="/data"
server_backup_dir="leo_g@69.163.35.116:/backup/data"
log_dir="backuperrors.txt"
#My own man pages say nothing about what 0 means, but from digging around, it seems to mean the current process group. Since the script get's it's own process group, this ends up sending SIGHUP to all the script's children, foreground and background.
#http://stackoverflow.com/questions/1644856/terminate-running-commands-when-shell-script-is-killed
trap 'kill -HUP 0' EXIT

#FUNCTION TO USE RYSNC TO BACKUP DIRECTORIES
function backup () {

if rsync -avz --delete $backup_dir $server_backup_dir  &>>$log_dir
then
du -sh $backup_dir| mail -s "backup succeeded $backup_dir" leo
else
mail -s "rysnc failed on $backup_dir" leo@leog.in < $log_dir
return 1
fi
}


#CHECK IF INOTIFY-TOOLS IS INSTALLED
type -P inotifywait &>/dev/null || { echo "inotifywait command not found."; exit 1; }

#INFINITE WHILE LOOP
while true
do

#START RSYNC AND ENSURE DIR ARE UPTO DATA
backup  || exit 0

#START RSYNC AND TRIGGER BACKUP ON CHANGE
inotifywait -r -e modify,attrib,close_write,move,create,delete  --format '%T %:e %f' --timefmt '%c' $backup_dir  &>>$log_dir && backup

done

